---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
suites:
- name: primary
  run_list:
  - recipe[repmgr]
  attributes: { }
- name: follower
  run_list:
  - recipe[repmgr]
  attributes: { }

clusters:
  default:
  - primary
  - follower