---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list:
    - recipe[postgresql::server]
    - recipe[postgresql::contrib]
    - recipe[repmgr]
  attributes:
    postgresql:
      password:
        postgres: 32e12f215ba27cb750c9e093ce4b5127
      config:
        listen_addresses: 0.0.0.0
    repmgr:
      addressing:
        self: localhost
      replication:
        role: master
        user_password: 32e12f215ba27cb750c9e093ce4b5127
        database: pgbench
      config:
        node: 1
      data_bag:
        encrypted: false
- name: postgresql-92
  run_list:
    - recipe[repmgr::apt_pgdg_postgresql]
    - recipe[postgresql::server]
    - recipe[postgresql::contrib]
    - recipe[repmgr]
  attributes:
    package_installer:
      packages:
        libpq5:
          version: 9.2.5-1.pgdg12.4+1
        libpq-dev:
          version: 9.2.5-1.pgdg12.4+1
    postgresql:
      enable_pgdg_apt: true
      version: 9.2
      password:
        postgres: 32e12f215ba27cb750c9e093ce4b5127
      config:
        listen_addresses: 0.0.0.0
      client:
        packages:
          - postgresql-client-9.2
      contrib:
        packages:
          - postgresql-contrib-9.2
    repmgr:
      addressing:
        self: localhost
      replication:
        role: master
        user_password: 32e12f215ba27cb750c9e093ce4b5127
        database: pgbench
      config:
        node: 1
      data_bag:
        encrypted: false
